name: offline_barcode_cashier_camera_fix
description: Offline barcode cashier and inventory app.
publish_to: "none"
version: 1.0.16+17
environment:
  sdk: ">=3.7.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.2
  image_picker: ^1.1.2
  google_mlkit_barcode_scanning: ^0.13.0
  share_plus: ^10.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
